name: build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

env:
  PROJECT: lua-language-server
  BIN_DIR: bin

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-18.04,   target: linux,   platform: linux-x64, zip: x86_64-linux    }
          - { os: macos-11,       target: darwin,  platform: darwin-x64, zip: x86_64-macos   }
          - { os: windows-latest, target: windows, platform: win32-x64, zip: x86_64-win32    }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actboy168/setup-luamake@master
      - run: luamake -platform ${{ matrix.platform }}

      - name: Create bin archive
        id: vars
        shell: bash
        run: |
          # Package version
          if [[ $GITHUB_REF = refs/tags/* ]]; then
            PKG_VERSION=${GITHUB_REF##*/}
          else
            PKG_VERSION=${GITHUB_SHA:0:7}
          fi

          # Package name w/ version
          PKG_BASENAME="${{ matrix.zip }}"

          # Full name of the tarball asset
          PKG_NAME="${PKG_BASENAME}.zip"

          7z -y a ${PKG_NAME} ${{ env.BIN_DIR }} main.lua debugger.lua LICENSE locale doc meta script

          echo ::set-output name=PKG_BASENAME::${PKG_BASENAME}
          echo ::set-output name=PKG_NAME::${PKG_NAME}
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.PKG_BASENAME }}
          path: |
            ${{ steps.vars.outputs.PKG_NAME }}

      # - name: Publish release assets
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     generate_release_notes: true
      #     files: | # fix PKG_PATH!
      #       ${{ steps.vars.outputs.PKG_PATH }} 
  create-extension:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - name: "Create "
        shell: bash
        run: |
          ls -l 
          ls -l x86_64-linux
          cp x86_64-linux/x86_64-linux.zip defold/lsp-lua-language-server/plugins/bin
          cp x86_64-macos/x86_64-macos.zip defold/lsp-lua-language-server/plugins/bin
          cp x86_64-win32/x86_64-win32.zip defold/lsp-lua-language-server/plugins/bin
          ls -l defold
          ls -l defold/lsp-lua-language-server/plugins/bin
          7z -y a archive.zip defold/*
      - name: Publish release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: archive.zip
